export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_PENDING = 'GET_EMPLOYEE_PENDING';
export const GET_EMPLOYEE_FULFILLED = 'GET_EMPLOYEE_FULFILLED';
export const GET_EMPLOYEE_REJECTED = 'GET_EMPLOYEE_REJECTED';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_PENDING = 'ADD_EMPLOYEE_PENDING';
export const ADD_EMPLOYEE_FULFILLED = 'ADD_EMPLOYEE_FULFILLED';
export const ADD_EMPLOYEE_REJECTED = 'ADD_EMPLOYEE_REJECTED';
