export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_PENDING = 'GET_EMPLOYEE_PENDING';
export const GET_EMPLOYEE_FULFILLED = 'GET_EMPLOYEE_FULFILLED';
export const GET_EMPLOYEE_REJECTED = 'GET_EMPLOYEE_REJECTED';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_PENDING = 'ADD_EMPLOYEE_PENDING';
export const ADD_EMPLOYEE_FULFILLED = 'ADD_EMPLOYEE_FULFILLED';
export const ADD_EMPLOYEE_REJECTED = 'ADD_EMPLOYEE_REJECTED';


export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_PENDING = 'UPDATE_EMPLOYEE_PENDING';
export const UPDATE_EMPLOYEE_FULFILLED = 'UPDATE_EMPLOYEE_FULFILLED';
export const UPDATE_EMPLOYEE_REJECTED = 'UPDATE_EMPLOYEE_REJECTED';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_PENDING = 'DELETE_EMPLOYEE_PENDING';
export const DELETE_EMPLOYEE_FULFILLED = 'DELETE_EMPLOYEE_FULFILLED';
export const DELETE_EMPLOYEE_REJECTED = 'DELETE_EMPLOYEE_REJECTED';

export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const SEARCH_EMPLOYEE_PENDING = 'SEARCH_EMPLOYEE_PENDING';
export const SEARCH_EMPLOYEE_FULFILLED = 'SEARCH_EMPLOYEE_FULFILLED';
export const SEARCH_EMPLOYEE_REJECTED = 'SEARCH_EMPLOYEE_REJECTED';